### ISSUE TITLE
Assigning environment name in properties file leads to exception

### ISSUE THREAD

**Issue by makshilpa** [Microsoft/Availability-Monitor-for-Kafka#19]
In the latest code merged to the vipstatus branch the App.java has the following code:
           
if((appProperties.environmentName == null || appProperties.environmentName.equals("")) && line.hasOption("cluster")) {
                appProperties.environmentName = line.getOptionValue("cluster");
            } else {
                throw new IllegalArgumentException("cluster name must be provided either on the command line or in the app properties");
            }

This leads to exception whenever `-cluster` is missing instead of just using the `environmentName` in the app properties.

**Comment by alyssasallean** [comment]
apologies, it was a bad change on my part. Pull request for the fix is out: 
https://github.com/Microsoft/Availability-Monitor-for-Kafka/pull/20
